[package]
name = "regulome"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"lib/*",
	"boot",
	"kern"
]

[workspace.dependencies]
log = "0.4.21"
elf = {version = "0.7.4", default-features = false }
x86_64 = {version = "0.15.1", default-features = false, features = ['instructions']}
